### ISSUE TITLE
A bug has occurred

### ISSUE THREAD

**Issue by z007XL** [ParisNeo/prompt_translator#12]
A bug has occurred, and the Chinese negative prompt word is not available. The software did not translate or load negative prompt words, only positive prompt words were translated.I hope you can solve it

**Comment by z007XL** [comment]
I have checked all options


Enable translation
Translate negative prompt

**Comment by zhanghongyong123456** [comment]
> I have checked all options
> 
> Enable translation Translate negative prompt

You just need to change this place,  
![image](https://user-images.githubusercontent.com/48466610/231696209-9ed363b4-b672-4251-8cfc-d18a5cf6068f.png)

![image](https://user-images.githubusercontent.com/48466610/231695641-ad78c3b6-f80b-4680-82d5-30ef343ad8dc.png)

**Comment by z007XL** [comment]
> 好吧，这可以暂时解决问题，但您将无法禁用翻译负面提示。我现在正在度假，无法访问我的电脑。复选框的值似乎与我预期不符。
> 
> 我已经进行了盲目修复，因为我现在无法对其进行测试。请告诉我它是否确实解决了您的问题。

Prompt errors, as indicated in screenshots.  

![QQ浏览器截图20230414230608](https://user-images.githubusercontent.com/130570670/232082297-d6ed5936-a7fa-41f9-ae6d-af7607f9d977.png)

**Comment by z007XL** [comment]
![image](https://user-images.githubusercontent.com/130570670/232091908-a69e27b9-35fa-4281-ba4d-9106963bcee6.png)
![image](https://user-images.githubusercontent.com/130570670/232092504-94b753df-42b4-45b6-a0f5-17e80bc6a188.png)

In version a0c8c82 the modification as shown in the figure solves the problemthx.  
thx.


> > 我已经检查了所有选项
> > 启用翻译 翻译否定提示
> 
> 你只需要改变这个地方， ![图像](https://user-images.githubusercontent.com/48466610/231696209-9ed363b4-b672-4251-8cfc-d18a5cf6068f.png)
> 
> ![image](https://user-images.githubusercontent.com/48466610/231695641-ad78c3b6-f80b-4680-82d5-30ef343ad8dc.png)

**Comment by z007XL** [comment]
> 
Thank you very much. This issue has been resolved in the previous section. Wishing you a pleasant holiday trip! If your travel destination is considering China, you are welcome to visit China. I can provide you with travel guidance in Guangzhou, China.

**Comment by z007XL** [comment]
> Well, that can fix the problem temporarily but you wouldn't be able to disable translating the negative prompt. I am on a vacation right now and have no access to my PC. It seems that the value of the checkbox is not as I expected.
> 
> I have made a blind fix as I can't test it right now. Please tell me if it did fix your problem.

Thank you very much. This issue has been resolved in the previous section. Wishing you a pleasant holiday trip! If your travel destination is considering China, you are welcome to visit China. I can provide you with travel guidance in Guangzhou, China.

**Comment by ParisNeo** [comment]
You're welcome

**Comment by ParisNeo** [comment]
I may visit china when I publish a paper. Thanks for your kind offer.
