### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by PPDzero-QA** [ParisNeo/prompt_translator#16]
Error running process: *\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\prompt_translator\scripts\main.py
Traceback (most recent call last):
  File "*\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 1 required positional argument: 'language'

**Comment by ParisNeo** [comment]
there was a problem In the code. It has been fixed. Can you pull the latest version and try again?
I am on vacation and don't have access to a PC to test.

**Comment by PPDzero-QA** [comment]
Fixed
