### ISSUE TITLE
The Russian language does not work

### ISSUE THREAD

**Issue by inck86** [ParisNeo/prompt_translator#17]
I checked in German - everything works. I turn on Russian - at first thinks for a long time, then incorrectly issues promt
![Screenshot_4](https://user-images.githubusercontent.com/119116007/232295235-eb945b13-bacc-4982-86bf-0e32bf10a4e9.png)

**Comment by ParisNeo** [comment]
My bad.
I've fixed this
Try to test again.

**Comment by inck86** [comment]
> My bad. I've fixed this Try to test again.

Yeap, it work now! Thx a lot!

**Comment by ParisNeo** [comment]
you're welcome
