### ISSUE TITLE
Model is [mbart-large-50-many-to-one-mmt], not [mbart-large-50-one-to-many-mmt]

### ISSUE THREAD

**Issue by ShionWakanae** [ParisNeo/prompt_translator#19]
in [README.md](https://github.com/ParisNeo/prompt_translator#readme)
usage section,  should refer to [Hugging Face model card](https://huggingface.co/facebook/mbart-large-50-many-to-one-mmt).

**`many-to-one`**, not `one-to-many`.

I followed the instruction and downloaded the model, 
same name and size, 
but it won't do the translation :cry:

Because of network condition, I didn't have a way to get the program to download the model automatically. So I did it manually, then I found the problem, It's not the model.

After I use the right model, the translation is OK, 
as below:

> Translating prompt to English from 中文
Initial prompt:一位中国的公主，骑在独角兽上。
Translated prompt:A Chinese princess, riding on a unicorn.

I think the code might be right, but readme is wrong.

**Comment by ParisNeo** [comment]
yeah sorry. I first used the many to many then I realized that I don't need that so I used the many to one butt forgot to change. Do you want to contribute by doing the modification and do a pull request?

**Comment by ParisNeo** [comment]
i did accept the PR
