### ISSUE TITLE
翻译有问题。。。。。请看图片 提示词给的太多了。。。

### ISSUE THREAD

**Issue by iconnoci** [ParisNeo/prompt_translator#7]
![Snipaste_2023-04-02_17-55-43](https://user-images.githubusercontent.com/22522962/229345777-c3c560c9-a6dd-484a-ad1d-00d7f1c69d0c.png)

**Comment by ParisNeo** [comment]
谢谢你的留言。不幸的是，我无法控制翻译模型，因为我使用 Facebook 的 MBART50 模型。如果您愿意，请向他们发送关于他们拥抱面孔的问题：
https://huggingface.co/facebook/mbart-large-50/discussions

**Comment by Skifoid** [comment]
Wrong language codes. Try to change in 'main.py' all zh_XX to zh_CN.

**Comment by ParisNeo** [comment]
Thank you very much. You are right.
I have repared this.
